### ISSUE TITLE
릴레이 채널 개수 변경시 버그

### ISSUE THREAD

**Issue by imwoo90** [imwoo90/flow_bending_machine#1]
릴레이 채널 - 채널 - 칼럼 순으로 매칭이 되는데 릴레이 채널 - 채널 매칭은 자동으로 이루어짐
개수 변경시 이러한 자동 매칭 매커니즘에 대한 고려가 없어 해당 부분에 대해 논의가 필요

**Comment by imwoo90** [comment]
1. 릴레이 개수, 각 릴레이 채널 변경시 초기 값을 일정하게 가져갈 것이냐??
2. 기존의 채널-칼럼 매칭에 대한 정보는 어떻게 할것인지?

**Comment by ghost** [comment]
1. 릴레이의 채널 수가 다른 릴레이로 교체 시, 릴레이 - 칼럼 - 방식 매칭을 초기화 및 규칙은 1-1-1 , 2-2-1 , 3-3-1 이렇게 가져감
2. 초기화
