### ISSUE TITLE
기판 테스트 중간 멈춤 버그

### ISSUE THREAD

**Issue by ghost** [imwoo90/flow_bending_machine#4]
기판 테스트 시 중간에 멈춤이 발생함
(1,2기판만 테스트 진행 그 이후 기판은 테스트 멈춤)

**Comment by ghost** [comment]
하드웨어 적인 주소 설정 문제였음.
주소가 순서대로 있지 않아서 (1,2,6 등으로 설정해놓음) 발생함.

**Comment by imwoo90** [comment]
기판이 없어도 통신 타입아웃이 나서 전체 테스트 완료가 느릴뿐이지 시스템이 멈추면 안되는데 이부분 확인 필요해 다시 오픈 함

**Comment by imwoo90** [comment]
Release 3.0.0 확인시 시스템 다운 현상 없음
